#!/bin/sh
# chkconfig: 123456 90 10
# init script for syslog-ng-monitor-agent
#
workdir=/home/pzolee/projects/syslog-ng-monitor-agent
 
start() {
    cd $workdir
    /usr/bin/python syslog-ng-monitor-agent.py --key=$workdir/server-key.pem --cert=$workdir/server-cert.pem --ca-cert=$workdir/cacert.pem >> /dev/null &
    echo "syslog-ng-monitor-agent started"
}
 
stop() {
    pid=`ps -ef | grep "[p]ython syslog-ng-monitor-agent.py" | awk '{ print $2 }'`
    echo "Stopping agent with pid: $pid"
    kill $pid
    sleep 2
    echo "syslog-ng-monitor-agent stopped"
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/syslog-ng-monitor-agent {start|stop|restart}"
    exit 1
esac
exit 0
